### ISSUE TITLE
Compatible with Badger2040W?

### ISSUE THREAD

**Issue by meub** [bablokb/circuitpython-clock#1]
I love this project. It's very similar to something I'm working on. Do you know if this would work with the Badger2040W to be able to support deep sleep and fetching data from a http endpoint once a day without any additional components (other than battery)? Thanks!

**Comment by bablokb** [comment]
Yes it works fine (just fetch the current version). Have a look at templates/configuration.py. You need an additional import (I will add it to the template, but currently it is missing). The lib for the pcf85063a rtc in the badger2040w should now be available from the circuitpython community bundle, so installation via circup should work.

**Comment by bablokb** [comment]
Oops: forgot to mention that there is no CircuitPython for the Badger2040W yet. But it on the way. If you are fine with building it yourself, you can head over to my CircuitPython clone (use branch badger_2040_w).

**Comment by meub** [comment]
I'm having a heck of a time building it myself. Downloading all the submodules is just taking forever on my slow connection right now. Any chance you could build a firmware.uf2 for the Badger2040W for me? I totally understand if not :)

**Comment by bablokb** [comment]
My PR for CircuitPython for Badger2040W has just been accepted. So it won't be long until you can download a version.

**Comment by meub** [comment]
I got CircuitPython installed and ran into a new issue. Looks like my board object doesn't have any DISPLAY attribute? Any idea why this could be the case? Currently it fails for me at line 60 of configuration.py. My board object just has: ['__class__', '__name__', 'A0', 'A1', 'A2', 'A3', 'GP0', 'GP1', 'GP10', 'GP11', 'GP12', 'GP13', 'GP14', 'GP15', 'GP16', 'GP17', 'GP18', 'GP19', 'GP2', 'GP20', 'GP21', 'GP22', 'GP26', 'GP26_A0', 'GP27', 'GP27_A1', 'GP28', 'GP28_A2', 'GP3', 'GP4', 'GP5', 'GP6', 'GP7', 'GP8', 'GP9', 'LED', 'SMPS_MODE', 'STEMMA_I2C', 'VBUS_SENSE', 'VOLTAGE_MONITOR', 'board_id']

**Comment by bablokb** [comment]
Strange. What is the value of board.board_id?

**Comment by meub** [comment]
board.board_id is raspberry_pi_pico_w

**Comment by bablokb** [comment]
This is the wrong firmware. You should download the firmware for the Badger2040W, not for the pico-w. See https://circuitpython.org/board/pimoroni_badger2040w/

**Comment by meub** [comment]
Oh whoops! Thanks so much for your help, it's working now :)

**Comment by bablokb** [comment]
So I assume we can close this issue?

**Comment by meub** [comment]
Yes, thank you!
